### PR TITLE
Adding initial Azure build

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
@richardbeare I'm getting the following problem with the Azure ubuntu build:
```

> devtools::install(c('/home/vsts/work/1'), args=c('--configure-vars=MAKEJ=4'))
Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

any ideas?

**Comment by richardbeare** [comment]
There appears to be a call to install devtools earlier on. Any sign of errors? Perhaps R_LIBS changes between stages?

Where are the logs?

**Comment by blowekamp** [comment]
Here are the logs:
https://dev.azure.com/SimpleITK-DevOps/SimpleITK/_build/results?buildId=159

**Comment by richardbeare** [comment]
Seems there are some errors in the devtools install (see bottom). Upshot, I think, is that we need the following additional packages
```bash
apt-get install -y ibcurl4-openssl-dev libgit2-dev libssh2-1-dev

```

the curl part is probably the only essential bit, but the others won't hurt

```r

ERROR: dependencies ‘curl’, ‘gh’ are not available for package ‘usethis’
* removing ‘/home/vsts/work/Rlibs/usethis’
ERROR: dependencies ‘httr’, ‘usethis’ are not available for package ‘devtools’
* removing ‘/home/vsts/work/Rlibs/devtools’

The downloaded source packages are in
	‘/tmp/Rtmp3PG1jq/downloaded_packages’
Warning messages:
1: In install.packages("devtools", lib = c("/home/vsts/work/Rlibs"),  :
  installation of package ‘curl’ had non-zero exit status
2: In install.packages("devtools", lib = c("/home/vsts/work/Rlibs"),  :
  installation of package ‘httr’ had non-zero exit status
3: In install.packages("devtools", lib = c("/home/vsts/work/Rlibs"),  :
  installation of package ‘gh’ had non-zero exit status
4: In install.packages("devtools", lib = c("/home/vsts/work/Rlibs"),  :
  installation of package ‘usethis’ had non-zero exit status
5: In install.packages("devtools", lib = c("/home/vsts/work/Rlibs"),  :
  installation of package ‘devtools’ had non-zero exit status

```

The curl dependencies:

------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your

git2r dependencies:

Unable to find the libgit2 library on this system. Building 'git2r'
   using the bundled source of the libgit2 library.

   To build git2r with a system installation of libgit2, please install:
     libgit2-dev   (package on e.g. Debian and Ubuntu)
     libgit2-devel (package on e.g. Fedora, CentOS and RHEL)
     libgit2       (Homebrew package on OS X)
   and try again.

ssh : 
   To build with SSH support, please install:
     libssh2-1-dev (package on e.g. Debian and Ubuntu)
     libssh2-devel (package on e.g. Fedora, CentOS and RHEL)
     libssh2 (Homebrew package on OS X)
   and try again.

**Comment by blowekamp** [comment]
The build look pretty good on azure. Linux looks successful, but getting the following on OSX:
```
Scanning dependencies of target SimpleITK_R
[100%] Building CXX object Wrapping/R/CMakeFiles/SimpleITK_R.dir/SimpleITKR_wrap.cxx.o
[100%] Building CXX object Wrapping/R/CMakeFiles/SimpleITK_R.dir/sitkRCommand.cxx.o
[100%] Building CXX object Wrapping/R/CMakeFiles/SimpleITK_R.dir/sitkRArray.cxx.o
[100%] Linking CXX shared module Packaging/SimpleITK/src/SimpleITK.so
/bin/sh: line 0: cd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpbxgKKH/R.INSTALL332cf757e1/SimpleITK/SITK/Build/SimpleITK-build/Wrapping/R/Packaging/SimpleITK/man: No such file or directory
make[5]: *** [Wrapping/R/Packaging/SimpleITK/src/SimpleITK.so] Error 1
make[4]: *** [Wrapping/R/CMakeFiles/SimpleITK_R.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
ERROR: configuration failed for package ‘SimpleITK’
* removing ‘/Users/vsts/agent/2.147.1/work/Rlibs/SimpleITK’
```
@richardbeare any idea?

**Comment by richardbeare** [comment]
Hi,
I can't find the failed osx build - which one is it?

**Comment by blowekamp** [comment]
It is not returning as a failure. But here it is:
https://dev.azure.com/SimpleITK-DevOps/SimpleITK/_build/results?buildId=228

It looks like there are some changes to the in the Travis patch which may effect the return value. I'm not sure if they are relevant here.

**Comment by blowekamp** [comment]
@richardbeare any luck navigating azure pipelines?

**Comment by richardbeare** [comment]
Not yet - I need to reproduce the problem on my laptop to figure out what is going on.

**Comment by richardbeare** [comment]
Hi,
@blowekamp 
```bash
/bin/sh: line 0: cd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpbxgKKH/R.INSTALL332cf757e1/SimpleITK/SITK/Build/SimpleITK-build/Wrapping/R/Packaging/SimpleITK/man: No such file or directory
```
I couldn't reproduce the problem on my laptop. My guesses:

The complaint is about the man folder in the R temporary folder, and the message appears to come from an attempt to change to that folder. This could be happening from [here](https://github.com/SimpleITK/SimpleITK/blob/52aece1ae938b76c530936f139deba57964ce497/Wrapping/R/CMakeLists.txt#L101) or [here](https://github.com/SimpleITK/SimpleITK/blob/52aece1ae938b76c530936f139deba57964ce497/Wrapping/R/CMakeLists.txt#L92)

What could the issues be? Shortage of free disk space - complete build take 12GB on my laptop. Failure to fetch the prebuilt documentation archive. No particular insight otherwise, I'm afraid. Would need to be able to log in and see the process in more detail.

**Comment by blowekamp** [comment]
I added "df -h" after the OSX build and there is the following output:
```
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk0s2   379Gi  273Gi  106Gi    72% 7546972 4287420307    0%   /
devfs          176Ki  176Ki    0Bi   100%     610          0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%       0          0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /home
```
So the disk is full

**Comment by richardbeare** [comment]
Is it possible to connect to azure during a build?

**Comment by blowekamp** [comment]
> Is it possible to connect to azure during a build?

Not in a way I have found. We can add some commands at the end.

**Comment by richardbeare** [comment]
I'm struggling a bit to find the problem. There is clearly a failure because the build stops after that section, and it shouldn't.

Is there any way to verify whether the copy of the Packaging sub directory happened properly? 
[here](https://github.com/SimpleITK/SimpleITK/blob/41ef28f262e3793e48bf6d8bbadf936fcf1a1840/Wrapping/R/CMakeLists.txt#L49) is where it is meant to happen. I can only guess there a problem or change with cmake. Otherwise I can't think of why we should be getting an error about the man subdirectory missing.

The stage at which it fails is a documentation generation step, which is meant to write out a doc file to provide some method documentation that CRAN would check for.

**Comment by richardbeare** [comment]
Adding a 
``` r
keep_outputs=TRUE
```
to the devtools::install call may leave something behind that can be listed.

**Comment by blowekamp** [comment]
So the fix in SimpleITK fixed things here with Azure too!

We still have the issue of the build script return success when the build fails. I'll have to create another issue for that.

With the update in the SimpleITK version, the R version should be updated too. After that this patch should be good to go.

**Comment by blowekamp** [comment]
The CI began failing due to "git2r" failing to install, which is one of many dependencies of devtools. I hope this proves to be a reliable tool to be installed in CI.

**Pull request merged**
