### PR TITLE
Added description of problem with unzip configuration on openSUSE

### PR DESCRIPTION
**Pull request by richardbeare**
This patch adds some explanation of an error that cropped up in the JSS review.

### CODE REVIEW

**Comment by blowekamp** [comment]
Nice work tracking this problem down!

I am not sure where to put this "errata". The current readme is a little sparse with not explicitly stating the requirements of devtools, and how to import the library. Do you think this type of problem with fix should go into a FAQ instead?

I was able to reproduce the issue:
```
$ docker pull opensuse
$ docker run --rm -i -t opensuse bash -l

docker#  zypper install R-base R-base-devel cmake gcc-c++ libcurl-devel openssl-devel libcurl-devel unzip git
docker# R

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-suse-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("devtools")
...
> library(devtools)
> devtools::install_github("SimpleITK/SimpleITKRInstaller")
Downloading GitHub repo SimpleITK/SimpleITKRInstaller@master
from URL https://api.github.com/repos/SimpleITK/SimpleITKRInstaller/zipball/master
Installation failed: error in running command
> options("unzip")
$unzip
[1] ""
```

I am getting a different error message and an empty initial value for the `unzip` option. Setting the option seems to get SimpleITK to start to build.

**Comment by richardbeare** [comment]
Probably needs to be in both, or at least a mention in the FAQ that the readme is there. I'll add a few more lines to the readme

**Comment by richardbeare** [comment]
I've extended the README and reordered things.

**Comment by blowekamp** [comment]
What is the status and relevance of this patch? Should it be merged?

**Comment by richardbeare** [comment]
I think we need an itemised plan. There's a collection of work that is
currently sitting as patches, but probably should end up as a combination
of FAQ/documentation entries and merges. I've been too busy with other
things to focus on them. Sorry about that.

1) New versions of devtools have different approaches to escaping arguments
passed through to build stages. This means that some of the examples in the
installer readme need to change. There are some matching changes inside the
configure script too.

2) General R configuration issues (SUSE stuff) probably doesn't belong in
the installer, but the installer readme will need a link to whereever it
ends up.

3) Windows - I haven't found a way of getting the correct linking behaviour
without the "EXTRA_FLAGS" style changes I've tested. Anything using the
current cmake infrastructure does a dynamic link against the thread library
and the result only runs inside MSYS2 shells.

4) Debian - haven't looked at the latest as I'm not sure how to reproduce
the testing stages.

**Comment by blowekamp** [comment]
This patch is old. I am closing it. If it is is still important/relevant please rebase and submit a new patch.

**Pull request closed without merging**
