### PR TITLE
Circle ci no testing

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
The command line in the memory usage artifact still shows static libraries in uses.

**Comment by richardbeare** [comment]
I know - probably made a typo somewhere. Planning to check when I have a
spare moment.

I'm also wondering whether strip/ranlib on the libraries will help.

I've not had to deal with this kind of issue for a long time - bigger
computers are so easy to get these days :-)

On Fri, Sep 16, 2016 at 10:42 AM, Bradley Lowekamp <notifications@github.com

**Comment by blowekamp** [comment]
Woot Woot! It compiled!!!! 

Looks like the run time path for the library just needs to be fixed.  The simplest way would be to set LD_LIBRARY_PATH. I don't think we are supporting "installing" R with shared libraries yet.

**Comment by blowekamp** [comment]
See #12  for latest iteration

**Pull request closed without merging**
