### PR TITLE
Update SimpleITK version to v1.0rc1 tag

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
@richardbeare @zivy 
Please test

**Comment by zivy** [comment]
Works for me, though I got the following warning message at the end of installation:
```
Reloading installed SimpleITK
Warning message:
`args` is deprecated 
```
I couldn't figure where 'args' is referred to. Possibly it is something from my older SimpleITK R installation or something else in my environment.

**Comment by blowekamp** [comment]
Great thanks for testing. Hopefully we can track that warming down before the final release.

**Comment by richardbeare** [comment]
I'm testing this now on mac and linux. I suspect the args warning may come from an updated devtools.

I also noticed I'm using a variable called args in the installer, which was a dumb idea because args is an R function that returns function arguments: args(mean)

**Comment by richardbeare** [comment]
The linux install worked for me, without the warning. I cloned and
installed locally though. This report seems to describe the issue :
https://github.com/hadley/devtools/issues/1373

**Pull request merged**
