### PR TITLE
Support for testing the SimpleITK R package and installer using Circl…

### PR DESCRIPTION
**Pull request by richardbeare**
…eCI facilities.

The circle.yml file contains various configuration options used by CircleCI, including
setting up R from the CRAN repo, installing an up to date version of cmake and
creating ssh connections to other nodes.

The build process for SimpleITK is very compute intensive and uses distcc to
run compilations on other nodes. Shared libraries are enabled to reduce
RAM requirements when linking. Failures due to 4GB limits are common
otherwise.

Testing is also distributed across multiple nodes.

### CODE REVIEW

**Comment by richardbeare** [comment]
Seems to compile successfully, including tests, and run most test successfully. There are still issues with the test dependencies, that you mentioned previously. Hopefully that will only require
a change of SITK tag.

**Comment by blowekamp** [comment]
This is great!

These test dependencies should be fixed in the master branch of SimpleITK!

**Comment by richardbeare** [comment]
I get the following error using master - very close otherwise, with the R package creation appearing successful.

/usr/bin/ld: /home/ubuntu/SimpleITKRInstaller/SITK/Build/GTest/lib/libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

**Comment by blowekamp** [comment]
Here is the rest of the error message:
/usr/bin/ld: /home/ubuntu/SimpleITKRInstaller/SITK/Build/GTest/lib/libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
distcc[93402] ERROR: compile (null) on localhost failed
make[5]: *** [bin/sitkCompareDriver-0.11-1] Error 1
make[4]: *** [Testing/Unit/CMakeFiles/sitkCompareDriver.dir/all] Error 2

This shows that the problem is with sitkCompareDriver. Not sure why I have not seen it any place else... I wonder what needs to happen to reproduce it.

**Comment by blowekamp** [comment]
Is there a proposed solution to this problem?

**Comment by richardbeare** [comment]
Not yet - I think it is to do with differing order of libraries when using
shared libraries. Haven't had a chance to confirm on other platforms or
figured out a way to change the library order in cmake

**Comment by richardbeare** [comment]
I've done some more playing around:

Turning off pthreads in the GTest configuration solves the link problem.
I've had to make a change to simpleitk/SuperBuild/External_GTest to achieve
that. I don't know what side effects might be, for example does that cause
ITK tests to run in single threaded mode?

As a result the whole process is more reliable and testing generally
completes. It is still possible for the memory limit to cause problems, but
it seems much rarer. It requires unfortunate timing producing a couple of
overlapping large compiles - I haven't seen the link stage causing problems
when shared libraries are enabled.

**Comment by blowekamp** [comment]
Very nice!  I don't think simpleitk needs ptheads for gtest. Can you make a simpleitk pull request for that change?

**Comment by blowekamp** [comment]
Is this good to go? Do we ween to update the SimpleITK TAG?

**Comment by richardbeare** [comment]
It needs to point to a tag which has gtest pthreads disabled. Not sure
whether that change has propogated through yet.

On Wed, Oct 26, 2016 at 12:20 AM, Bradley Lowekamp <notifications@github.com

**Comment by blowekamp** [comment]
This topic was merged into SimpleITK master here:
https://github.com/SimpleITK/SimpleITK/commit/b076418e52a5527b18eab9f2b80311a3721984ed

Can we use the hash?

**Comment by blowekamp** [comment]
I believe 1.0rc1 should have all the fixes to get this working...

**Comment by blowekamp** [comment]
This topic should be rebased onto the current master with SimpleITK 1.0rc1

**Comment by blowekamp** [comment]
Updated in #12

**Pull request closed without merging**
